### ISSUE TITLE
Function to read ICGEM data files

### ISSUE THREAD

**Issue by leouieda** [fatiando/harmonica#10]
**Description of the desired feature**

The [ICGEM Calculation Service](http://icgem.gfz-potsdam.de/) is an amazing resource to get gravity data. Their grids are in an ASCII format that can be tricky to parse because some values are included in the header. It would be great to have a function that reads the ICGEM file and returns an `xarray.Dataset`. 

This will really help with #9

**Comment by leouieda** [comment]
@santis19 would you mind porting fatiando/fatiando#421 to harmonica? There a few changes that will need to be done:

- [ ] Replace the `asserts` with proper `if ... raise` checks
- [ ] Use `**kwargs` to pass arguments to `numpy.loadtxt` instead of manually specifying `usecols`
- [ ] Return an `xarray.Dataset` instead of a `dict`. You can pass the entire header string as metadata. 
- [ ] Probably no need to read in the latitude and longitude limits. But we do need to parse the grid shape from the header.

The function can go in a new `harmonica/io.py` module and then import it in `harminca/__init__.py`. This way we can use it as `harmonica.load_icgem_gdf` instead of having to load several modules.

**Comment by santis19** [comment]
@leouieda I've just started working on this.
As soon I have a respectable code I'll PR.

I have one question: what about tests functions for this function?
Are you intending to leave tests functions for the future or to only merge PRs with 100% test coverage?

**Comment by santis19** [comment]
We need `xarray` to be listed in `environment.yml`.
Do you want me to add it on the PR I'm currently working on?

**Comment by leouieda** [comment]
>  Are you intending to leave tests functions for the future or to only merge PRs with 100% test coverage?

Yep, test coverage is a must for merging. Github automatically bars merging if coverage of the diff is less than 80%. Leaving it for later is a recipe for never doing it, as I learned from fatiando.

> what about tests functions for this function?

The fatiando version has some tests that you can use, if I'm not mistaken. But try to see if you can get 100% coverage. It's worth the exercise as you learn a lot about designing good code. For example, it might be best to try to allow a file name or a file object as input. This way we can use StringIO for testing.

>  Do you want me to add it on the PR I'm currently working on?

Please include it in the `environment.yml`, `requirements.txt`, `setup.py`, and `doc/install.rst`.
