### ISSUE TITLE
Avoid stacking coordinates on tesseroid forward modelling

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#100]
**Description of the desired feature**

As raised by @leouieda on #98 and #86, we should avoid stacking `coordiantes` arrays in order to avoid unnecessary memory allocation. Therefore, `coordinates` must be a tuple of 1d numpy arrays. This issue was already solved on point mass and prisms forward models, but the tesseroids forward model still stacks `coordinates`.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by santisoler** [comment]
After playing with Numpy arrays I found out that:

- `np.vstack` allocates memory:
    ```python    
    import numpy as np
    x = np.linspace(0, 3, 4)
    y = np.linspace(0, 3, 4)
    c = np.vstack((x, y))
    x[0] = 1e3
    print(x)
    >>> [1000.    1.    2.    3.]
    print(c)
    >>> [[0. 1. 2. 3.]
    >>>  [0. 1. 2. 3.]]
    ```
- `np.atleast().ravel()` does not allocate:
    ```python
    import numpy as np
    x = np.linspace(0, 3, 4)
    y = np.linspace(0, 3, 4)
    c = tuple(np.atleast_1d(i).ravel() for i in (x, y))
    x[0] = 1e3
    print(x)
    >>> [1000.    1.    2.    3.]
    print(c)
    >>> (array([1000.,    1.,    2.,    3.]), array([0., 1., 2., 3.]))
    ```
- But when applying `astype()`, we do allocate memory:
    ```python
    import numpy as np
    x = np.linspace(0, 3, 4)
    y = np.linspace(0, 3, 4)
    c = tuple(np.atleast_1d(i).ravel().astype(float) for i in (x, y))
    x[0] = 1e3
    print(x)
    >>> [1000.    1.    2.    3.]
    print(c)
    >>> (array([0., 1., 2., 3.]), array([0., 1., 2., 3.]))
    ```

So, even if we decide to drop the `vstack` approach to build the coordinates array, we are still allocating memory when setting the data-type. One way to prevent allocating memory is not to change the data-type, although this may cause some accuracy issues if a wrong data-type is passed. Besides, the memory allocation is only performed once per forward model, so I don't think we are loosing so much computation time and the memory consumption is not big because the `coordinates` array is overwritten.

Are my thoughts right? What do you think?

**Comment by leouieda** [comment]
Some of these copies might have to be necessary if changing the input tesseroids array. But ideally we shouldn't be copying memory unnecessarily. I would be best to stop casting altogether and leave that up to the user to avoid needless duplication of memory.
