### ISSUE TITLE
Replace the Rio magnetic data with Great Britain open dataset

### ISSUE THREAD

**Issue by leouieda** [fatiando/harmonica#101]
The Rio data is provided by [CPRM](http://geosgb.cprm.gov.br/) but it doesn't really have a license. It would be best if we replaced it with an actually open dataset (with a permissive license). 

The British Geological Survey provide a [full aeromagnetic survey](https://www.bgs.ac.uk/products/geophysics/aeromagneticRegional.html) of Britain with a [permissive open license](http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/). I would be happy to have a different dataset from outside North America and Europe but this might be the best we can get right now. We can always add another dataset later.

If this data file is too big (10s of Mb compressed), we can only host an interesting portion of it with nice anomalies.

What needs to be done:

* Open and plot the dataset to see if it's worth using.
* Convert the coordinates from [OSGB36](https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid) to WGS84.
* Keep only the useful columns (survey name/year, line number, longitude, latitude, flight height, IGRF90 corrected anomaly)
* Save in compressed CVS and check the file size.
* Commit archive and add to Pooch registry `harmonica/datasets/registry.txt`
* Create a loading function and gallery example

**Comment by nshea3** [comment]
Hi,

I'd like to help out with this.

I opened up the aeromag csv and threw together a quick scatterplot: 

![image](https://user-images.githubusercontent.com/25097799/66040981-09086900-e519-11e9-9326-0c8772780892.png)

Color is MAG_IGRF90 value. I will post a gist later today. 

The compressed CSV of the interesting columns is only 4 MB (xz format). 

Nick

**Comment by santisoler** [comment]
Hi @nshea3! We are glad you want to contribute with Harmonica! :clap:

Please, read our [Contributors Guidelines](https://github.com/fatiando/harmonica/blob/master/CONTRIBUTING.md) and our [Code of Conduct](https://github.com/fatiando/harmonica/blob/master/CODE_OF_CONDUCT.md) before you start.
Remember that any contribution to Harmonica (or to any Fatiando a Terra project) should be made as a Pull Request. Posting a gist is very helpful when sharing snippets of code, but not when trying to contribute to an already existing project. If you have any doubts on how to perform any of the steps needed to get your code finally merged, don't hesitate to ask, we are willing to help!
Feel free to open your PR whenever you're ready, we can start discussing it or solving specific issues on the PR interface.

**Comment by nshea3** [comment]
Thank you! I was just planning to share the code snippet I used to plot the data and perform the coordinate transformation, so nothing that I'm looking to check into the repo.  

I will open a pull request shortly and move the discussion over there. I look forward to your feedback!

Nick
