### ISSUE TITLE
Add option to avoid sanity checks on forward models

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#108]
**Description of the desired feature**

The current forward models for [prisms](https://www.fatiando.org/harmonica/dev/api/generated/harmonica.prism_gravity.html#harmonica.prism_gravity) and [tesseroids](https://www.fatiando.org/harmonica/dev/api/generated/harmonica.tesseroid_gravity.html#harmonica.tesseroid_gravity) perform sanity checks on the input arrays. Most of them involve looping through computation points and sources, resulting in a task that could take a significant amount of time. Although this time is negligible when performing a single forward computation, it could be problematic when several forward computations are needed, e.g. on inversions. Would be nice to include an optional argument to avoid performing these sanity checks and also add a notice to only disable them when it's really needed and in a very careful way.

A cool name for the new optional argument could be `disable_checks` that should be False by default.
The sanity checks that should be optionally disabled are the one that make use of a private function, like [_check_prisms()](https://github.com/fatiando/harmonica/blob/master/harmonica/forward/prism.py#L103).

The new optional argument should have a description on the docstring, explaining when you would set it to True and its possible unwanted consequences.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by Pralkarz** [comment]
Hello. I would like to work on this issue.

**Comment by santisoler** [comment]
Hi @Pralkarz! We are very happy with your will to help!
You can start reading the [Contributing Guidelines](https://github.com/fatiando/harmonica/blob/master/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/fatiando/harmonica/blob/master/CODE_OF_CONDUCT.md) before opening the PR.

Feel free to ask for help, we are willing to give you a hand with any trouble you encounter.
Open the PR whenever you are ready!
