### ISSUE TITLE
Split up the isostasy code into a separate package

### ISSUE THREAD

**Issue by leouieda** [fatiando/harmonica#123]
Since I've been rethinking a lot of the Fatiando packages lately, Harmonica is going to escape. If our goal is to be a "gravity and magnetics" package, then isostasy/flexure calculations don't really fit in here. Sure, we use them in conjunction with gravity but actual calculations don't really have any gravity in them. 

I propose moving this type of function to a separate isostasy/flexure package. With the new [package template](https://github.com/fatiando/package-template/), it's a lot easier to create new packages and we can release them as often as we need (without waiting for unrelated things in Harmonica to be resolved). Maintenance is not that complicated anymore and a lot of our process is automated. So maintaining a single large package is not really easier now. This is why this whole split of `fatiando` is [happening in the first place](https://www.leouieda.com/blog/future-of-fatiando.html). 

As for possible names, the following aren't taken on PyPI:

* Roots
* Isostasy
* Isostatic
* Jiboia (a play on potuguese words: jiboia is a [boa constrictor](https://en.wikipedia.org/wiki/Boa_constrictor) [snake] and boia means "float" or "bouy")

**Comment by santisoler** [comment]
I think having a package template and releasing with a lot of automation is a great advantage when we want to take this kind of decisions.

Regarding the name, I like having latin names for our packages, specifically for this one that is completely based on the Archimedes principle (who was born in Sicily).
So, I would propose to translate isostasy to a latin language. For example, in Spanish, it translates to **isostasia**. I'm not entirely sure, but according to [this dictionary](https://www.linguee.com/english-italian/search?source=auto&query=isostasy) it's the same for Italian. It's free on Pypi and very easy to remember.

Other names came up to my head, like:
- gallegia (conjugation of the Italian gallegiare verb than means *to float*)
- gavitello (a small buoy, also in Italian)

**Comment by leouieda** [comment]
I like *isostasia*. Reading it in English kind of sounds like [Fantasia](https://en.wikipedia.org/wiki/Fantasia_(1940_film)) which makes for nice pun opportunities.

**Comment by leouieda** [comment]
Gave up on this idea for now because isostasy is tightly coupled with gravity anyway.
