### ISSUE TITLE
Repeated points on sample datasets downloaded from ICGEM

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#124]
**Description of the problem**

We currently have three sample datasets that have been downloaded from the [ICGEM Calculation Service](http://icgem.gfz-potsdam.de/calcgrid):
- Earth Topography
- Earth Gravity
- Earth Geoid

Each of these models has been created on a regular grid in a geodetic coordinate system.
On the latitude direction they span between -90 and 90 degrees, while on the longitudinal one they do so between -180 and 180 degrees.
The problem is that the -180 and 180 longitudinal degrees are equivalent, therefore each dataset contains one row of repeated values.

Would be nice to regenerate and upload these datasets without any repeated values.
What has to be done?
1. Fetch each dataset with the existing functions (e.g. `hm.datasets.fetch_topography_earth()`).
2. Remove the repeated longitudinal coordinate and its corresponding data values.
3. Save the new dataset to a NetCDF file (`.nc`)
4. Compress it to a `.xz` file.
5. Replace the existing files on `data` with the new ones.
6. Get the sha256 hash of the new file and update `harmonica/datasets/registry.txt`

**Comment by leouieda** [comment]
Alternatively, we could keep the datasets as they are and only drop the point when we load them.

**Comment by santisoler** [comment]
Since we are moving every dataset to Ensaio, I'm closing this issue.
