### ISSUE TITLE
Airy Isostasy calculations

### ISSUE THREAD

**Issue by leouieda** [fatiando/harmonica#15]
**Description of the desired feature**

We need a function that calculates the Moho depth from topography based on an Airy isostatic model. This will be useful for calculating isostatic gravity anomalies, for example.

The function only needs to know the topographic height values and crust, mantle, and water densities (optional):

```python
def isostasy_airy(topography, density_crust, density_mantle, density_water=None):
    ...
    return moho_depth
```

If water density is not given, negative topography will be ignored and the Moho depth for those values will be set to NaN.

The function can live in a new `isostasy.py` module.

I'm entirely happy with the function name. Any suggestions?

**Comment by aguspesce** [comment]
Hi @leouieda 
I'm interested in developing this function. This would be my first time, but @santis19  will be helping me to do it. 
I have already written something for Airy isostatic model, so I would have to put it in format and  satisfy the harmonica's requirements. 
I will start a PR and there we can discuss the Airy code.

**Comment by leouieda** [comment]
@aguspesce thanks for helping out! It's much appreciated. I'll have a look at your pull request as soon as I can. Welcome to the team!
