### ISSUE TITLE
EQL docstrings ask for wrong coordinate systems

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#157]
**Description of the problem**

The `EQLHarmonic` and `EQLHarmonicSpherical` classes inherit some methods from `verde.BaseGridder` along with their corresponding docstrings. These methods are meant to be used either with geographic or Cartesian coordinates, although `EQLHarmonic` and `EQLHarmonicSpherical` have well-defined needs of coordinate systems.

The inherited methods that ask for coordinates (or regions) are:
- `grid`
- `scatter`
- `profile`

Also, some of the previous methods create `xarray.DataArray`s or `xarray.Dataset` assigning specific coordinate names by default (like `northing` and `easting`). Although we know that for `EQLHarmonicSpherical` these coordinates should be `longitude` and `latitude`.

Would be nice to overwrite the docstrings of these methods and change the default arguments passed to each one of them if needed.

**Comment by santisoler** [comment]
Just a quick though: maybe we could create separate `BaseGridder` classes on `verde` for different coordinate systems (what could help to fatiando/verde#231).

**Comment by leouieda** [comment]
That's a good point. It might be better to have a `BaseSphericalGridder` or `BaseGeographicGridder` that has a bit more knowledge that things are supposed to be spherical/geodetic. The `EQLHarmonic` should be fine with `BaseGridder` right? Would you mind opening an issue for that in Verde? It will be useful when we implement spherical splines in Verde as well.

**Comment by leouieda** [comment]
Upon further discussion, we realised that this could be done with a documentation upgrade in the base classes to avoid saying "Cartesian" or "geographic". The default coordinate names could also be gotten from the class itself if it defines a `dims` attribute, which could default to `["northing", "easting"]` in the base class.

**Comment by santisoler** [comment]
After a discussion with @leouieda, we decided it's better to keep a single `BaseClass` layer, but making its docstrings more general and adding `dims` as a class variable, so we can define them every time we subclass it.

**Comment by santisoler** [comment]
This has been fixed by fatiando/verde#240
