### ISSUE TITLE
Convert geocentric geodetic coordinates into geocentric Cartesian coordinates

### ISSUE THREAD

**Issue by birocoles** [fatiando/harmonica#159]
Currently, harmonica has functions for converting geocentric geodetic to geocentric spherical coordinates and vice versa. It would be useful to include a functions for converting geocentric geodetic to geocentric Cartesian coordinates. These functions would use the reference ellipsoids defined by `boule`.

**Comment by santisoler** [comment]
Thanks @birocoles for opening this issue. We have recently moved the coordinate conversions to `boule` (see #137), so this feature should`also live inside `boule` instead of `harmonica`. Would you open a similar one over there?

**Comment by birocoles** [comment]
Yes!

**Comment by leouieda** [comment]
Transfered to fatiando/boule#29. Just found out that there is a "Transfer issue" button that will move the issue to the right repository. No need to open a new one.

**Comment by santisoler** [comment]
> Transfered to [fatiando/boule#29](https://github.com/fatiando/boule/issues/29). Just found out that there is a "Transfer issue" button that will move the issue to the right repository. No need to open a new one.

Great feature for projects with many libraries like Fatiando!
