### ISSUE TITLE
Upward continuation in frequency domain

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#162]
**Description of the desired feature**

Based on requests made on the Slack group, would be nice to have upward continuation in the frequency domain implemented in Harmonica. The old Fatiando package had some frequency domain features, although it didn't have the best design for them. One possible option is to add [`xrft`]() as a dependency and use it to compute the FFT of the magnetic/gravity grid.
Also, would be nice to add functions that implements Burg's method ([Fedi, 2012](https://academic.oup.com/gji/article/188/1/103/632206)) for padding the grids before computing FFT.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by leouieda** [comment]
I agree. The grid padding part is currently being developed in xarray itself (pydata/xarray#3596). It might be good to keep an eye on the discussion and try out the code on your own use cases to let them know if it fails.

**Comment by LL-Geo** [comment]
Following the release of v0.6.0 https://github.com/fatiando/harmonica/issues/386, we are able to run upward continuation[see example](https://www.fatiando.org/harmonica/latest/user_guide/transformations.html).
I'll close this one as well 😎
