### ISSUE TITLE
Add upward argument to EQLHarmonic grid and scatter methods

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#163]
**Description of the desired feature**

Would be better to explicitly ask for the upward coordinate when trying to use EQL to predict on grid and scatter points. Currently it must be passed as the keyword argument `extra_coords`, which is not explicitly present in Harmonica documentation.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by leouieda** [comment]
Shoot, I forgot what we discussed about this. In the end, was I in favour or against adding this? :slightly_frowning_face:

**Comment by santisoler** [comment]
Haha as far as I remember we agreed to try to create a base class for all EQL classes, where these methods can be redefined to add any specific argument they may need.

I've opened an issue on that (#165) and a WIP PR (#166) to start working on that.

**Comment by leouieda** [comment]
Right, I saw that right after posting this :facepalm:
