### ISSUE TITLE
Remove default values on EQL gridders

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#171]
**Description of the desired feature**

I think it's better to not set default values for any EQL parameter.
The existence of default values for any EQL parameter may lead to unexperienced users to bad interpolations, assuming those values are wisely chosen by the Harmonica developers (which is absolutely false). The best choice for the values for these parameters are case-specific and we should encourage to apply cross-validation to obtain them.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by leouieda** [comment]
The general idea is to provide users with a order of magnitude for the parameters. We can emphasise that the value needs to be set with a tutorial (linked in the docstring). Like this: https://www.fatiando.org/verde/dev/tutorials/model_selection.html#the-importance-of-tuning

**Comment by leouieda** [comment]
But it might be good to mention this in the docstring. What the parameter means and why this value is set as default.

**Comment by santisoler** [comment]
We decided that it's better to leave them for two reasons:
- We want EQL to work without overriding any default parameter. If we remove default values (and replace them by `None`), we would get weird errors if we don't pass valid values to them.
- It's good to have default values for giving users a sense of order of magnitude of that parameters.

Maybe, as an alternative, we could improve these default values.
