### ISSUE TITLE
Remove sample datasets after moved to Rockhound

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#179]
**Description of the desired feature**

On the last community call we decided to move all sample datasets in Fatiando to Rockhound.
Harmonica datasets are being moved to Rockhound on https://github.com/fatiando/rockhound/pull/84.
After it is merged, we should remove the harmonica.datasets along with the data folder. Besides, all gallery examples should download their data from Rockhound, therefore it should be added as an optional dependency.

**Are you willing to help implement and maintain this feature?** Yes, but would leave to anyone that wants to tackle it.

**Comment by lperozzi** [comment]
This means that 

```python notebook
# Read South Africa topography
south_africa_topo = hm.datasets.fetch_south_africa_topography()
```
will not work anymore right? I tried to fetch it in a environment with the last `prisms-layer` branch installed, but I have the following error:

```python notebook
HTTPError: 404 Client Error: Not Found for url: https://github.com/fatiando/harmonica/raw/master/data/south-africa-topography.nc.xz

```

**Comment by santisoler** [comment]
Sorry for the delay! The notification was buried among others.

Yes, we probably end up ditching the `harmonica.datasets` module, but I don't expect to do that before the next release.

The issue with the South Africa topography raises because that dataset hasn't been merged to `master` yet. That's why you get that error. A quick solution in order to run the tests from data branch is to manually copy the `south-africa-topography.nc.xz` file to the default cache folder of Harmonica. This way, when the dataset is fetched through `hm.datasets.fetch_south_africa_topography()`, Harmonica won't try to download it because it's already on the cache folder.
