### ISSUE TITLE
Add example for applying cross-validation with EQLHarmonic

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#185]
**Description of the desired feature**

Would be nice to have an example or a documentation page to show how to choose the best set of parameters while gridding gravmag data using `EQLHarmonic`. A good idea would be to start with one of the sample datasets and:

1. calculate gravity disturbance (using Boule),
2. project data into Cartesian coordinates,
3. use `itertools` to create set of parameters (`damping` and `relative_depth`),
4. use `verde.BlockKFold` or `verde.BlockShuffleSplit` to cross-validate the gridder with each set of parameters,
5. get the best predictor,
6. grid data onto a regular grid in geodetic coordinates (using the `projection` argument on the `EQLHarmonic.grid()` method),
7. mask distant values with `vd.distance_mask`.

Maybe we would need to block-reduce (or crop) the original data to speed up computations, specially if CIs will have to run the example.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by santisoler** [comment]
For anyone wanting a tutorial for gridding gravmag, they can take a look at the notebook I presented at Transform2020: https://github.com/fatiando/transform2020-lightning/tree/master/santi

**Comment by mdtanker** [comment]
I was looking through the issues and noticed that this is still open, should it be closed with #305 and the following user guide https://www.fatiando.org/harmonica/dev/user_guide/equivalent_sources/eqs-parameters-estimation.html?

**Comment by santisoler** [comment]
Nice catch! Yes, we should close this now! Thanks @mdtanker!
