### ISSUE TITLE
Function to transform geodetic to geocentric spherical coordinates

### ISSUE THREAD

**Issue by leouieda** [fatiando/harmonica#20]
**Description of the desired feature**

The tesseroid modeling is done in geocentric spherical coordinates (longitude, geocentric latitude, radius) but the data is usually in geodetic coordinates (longitude, geodetic latitude, geometric height). Proj4 apparently only converts the latitudes (https://proj4.org/operations/conversions/geoc.html) but not the height to radius. We need a function that does this conversion so that we can use tesseroids appropriately. 

The function will use the current ellipsoid (`get_ellipsoid`) to do the conversion. Tests can use simplified ellipsoids to check that the computations are correct (like setting the flattening to 1 and axis to an integer). It could go into a new `harmonica/coordinates.py` module and should look like:

```python
def geodetic_to_geocentric(latitude, height):
    ...
    return geocentric_latitude, radius
```

**Comment by santis19** [comment]
@leouieda 
Seems a nice issue to be assigned to me. I would like to take Tesseroids related issues in the future, so this sounds a nice way to start.

**Comment by leouieda** [comment]
:+1:
