### ISSUE TITLE
Error in harmonica.tesseroid_gravity

### ISSUE THREAD

**Issue by lianghcug** [fatiando/harmonica#228]
**Description of the problem**
When I used the function "harmonica.tesseroid_gravity" to do forward modelling, I found that if the number of tesseroids was 14 (stored in file named "testinput.txt"), it worked well. However, when the number of tesseroids was about 70000 (stored in file named "SCS_Lon100Lon125_Lat0Lat30_Z100Z700_drhoF.txt"), it didn't work, there would be a word "killed" in the terminal, and then the program stopped automatically without getting any output.  

**Full code that generated the error**

(https://github.com/fatiando/harmonica/files/6331268/SCS_Lon100Lon125_Lat0Lat30_Z100Z700_drhoF.txt)
[testinput.txt](https://github.com/fatiando/harmonica/files/6331272/testinput.txt)

```python
PASTE YOUR CODE HERE
```
import matplotlib.pyplot as plt
import numpy as np
import verde as vd
import boule as bl
import harmonica as hm
from openpyxl import load_workbook 
import openpyxl

ellipsoid = bl.WGS84

region=[104, 124, 0, 27] 
shape=(55,41)
extra_coords=1 + ellipsoid.mean_radius # the height of observations
coordinates = vd.grid_coordinates(
    region=region,
    shape=shape,
    extra_coords=extra_coords,
)

inputfile = '/home/hl/share/SCS_Lon100Lon125_Lat0Lat30_Z100Z700_drhoF.txt'
####inputfile = '/home/hl/Documents/FatiandoCode/testinput.txt'
data = np.loadtxt(inputfile)

Glon = data[:,[0]]
Glat = data[:,[1]]
Gr = data[:,[2]]
Grho = data[:,[3]]

lx,ly,lr = 0.5,0.5,25e3

west,east,south,north = Glon - lx/2, Glon + lx/2, Glat - ly/2, Glat + ly/2
r = ellipsoid.mean_radius - Gr
bottom = r - lr/2
top = r + lr/2
tmp = np.append(west,east,axis=1)
tmp = np.append(tmp,south,axis=1)
tmp = np.append(tmp,north,axis=1)
tmp = np.append(tmp,bottom,axis=1)
tmp = np.append(tmp,top,axis=1)
tesseroid = tmp
density = Grho
    
gravity = hm.tesseroid_gravity(coordinates, tesseroid, density, field="g_z")

plt.contourf(*coordinates[0:2],gravity)
plt.colorbar(orientation="vertical", label="mGal")
plt.title("Gravity")
plt.xlabel("Longitude(degree)")
plt.ylabel("Latitude(degree)")
plt.show()

outputfile = '/home/hl/share/test.txt'
lonc = coordinates[0]
latc = coordinates[1]
f=open(outputfile,'w')

shp=gravity.shape
ln=shp[0]
col=shp[1]
for ii in range(ln):
    for jj in range(col):
        print("%0.4f\t%0.4f\t%0.4f\n" % (lonc[ii][jj],latc[ii][jj],gravity[ii][jj]),file=f)

f.close()

**Full error message**

```
PASTE ERROR MESSAGE HERE
```
There is no ERROR message, but there is a word  "killed" in the terminal, and then the program is stopped without any output.  

**System information**

* Operating system: Linux
* Python installation (Anaconda, system, ETS):system
* Version of Python: Python 3.6.9 64-bit
* Version of this package: harmonica.0.2.1
* If using conda, paste the output of `conda list` below:

<details>
<summary>output of conda list</summary>
<pre>

PASTE OUTPUT OF CONDA LIST HERE

</pre>
</details>

**Comment by santisoler** [comment]
Hi @lianghcug ! Sorry for my delayed response.

I just ran your code and it worked without any problem on my computer, also running Linux but with Python 3.8.

This is the image I get as output:
![Figure_1](https://user-images.githubusercontent.com/11541317/116885558-63d6da80-abfe-11eb-9687-a6edb215e60b.png)

Could you open your terminal, activate the environment that you were using to run this code (if any) and paste here the output of `conda list`?

If you run the script again, could you track your memory consumption? You could either use your System Monitor or `htop` in the terminal. I want to know if your computer runs out of memory when you run the script.

**Comment by lianghcug** [comment]
@santisoler Thank you very much. I think my problem must be lie on the memory, because my Linux system is built on a Virtual Machine.

**Comment by santisoler** [comment]
> @santisoler Thank you very much. I think my problem must be lie on the memory, because my Linux system is built on a Virtual Machine.

Although we develop Fatiando with the mind of being able to run scientific code on a laptop, if you handle too many data points or too many tesseroids, you might run out of memory, specially if your computer is on the lower end (<=4GB).

Regarding the virtualization, you can install and run any Fatiando package on any operative system (Linux, Mac OS, Windows), so feel free to try it out on your main OS if the VM is causing you trouble.

**Comment by santisoler** [comment]
@lianghcug I'm closing this because the problem seems to be related to a lack of memory due to the size of the model. Feel free to comment here if you find out anything else causing the problem. Also, feel free to ask any question on our Slack channel: contact.fatiando.org
