### ISSUE TITLE
Set dims to longitude and latitude in EQLHarmonic if projection is passed

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#233]
**Description of the desired feature**

When using `EQLHarmonic` to predict a given field on any set of points through the `grid` and `profile` methods we can optionally pass a `projection` in order to get the resulting object in geographic coordinates. Would be nice if these two methods change the `dims` to `("latitude", "longitude")` if `projection` is not `None` and the `dims` parameter hasn't been passed.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by santisoler** [comment]
@leouieda should we change this in Verde directly?

**Comment by leouieda** [comment]
@santisoler that seems like a decent default. Definitely should be changed in Verde directly.

**Comment by santisoler** [comment]
Closing this issue since this should be solved upstream.
