### ISSUE TITLE
Add option to set sources at constant depth in EQLHarmonicSpherical

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#251]
**Description of the desired feature:**

In the same way that #236 adds the option to set Cartesian sources at a constant depth beneath data points, the `EQLHarmonicSpherical` class should be able to do the same.

**Comment by indiauppal** [comment]
Constant depth is no longer needed as an option. The depth type has now been removed for the Cartesian sources ( #468 ). Only a relative depth is used and of a constant depth is wanted, coordinates at constant height can be passed instead.
