### ISSUE TITLE
Rename default branch to "main"

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#279]
We've been pushing this for too long, maybe we should start doing it sooner than later.
GitHub offers a nice interface for renaming the default branch. We should replace `master` for `main` on Actions workflows and in the pooch registry for the datasets.
I'm probably forgetting some places, so I would run a `git grep master` to find them.

**Comment by leouieda** [comment]
That's a 👍🏽 from me. PRs can be referenced to "main" afterwards.
