### ISSUE TITLE
Use another augmented assignment statement

### ISSUE THREAD

**Issue by elfring** [fatiando/harmonica#286]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/harmonica/forward/prism_layer.py b/harmonica/forward/prism_layer.py
index 0f24487..f5d4653 100644
--- a/harmonica/forward/prism_layer.py
+++ b/harmonica/forward/prism_layer.py
@@ -294,7 +294,7 @@ class DatasetAccessorPrismLayer:
                     + "of the layer of prisms."
                 )
         else:
-            reference = reference * np.ones(self.shape)
+            reference *= np.ones(self.shape)
         top = surface.copy()
         bottom = reference.copy()
         reverse = surface < reference
```

**Comment by santisoler** [comment]
Hi @elfring ! Sorry for the delayed reply, this Issue got buried and didn't see it in time.

Thanks for the catch! Surely, using `*=` is much better than the line we already have in there. Would you like to open a PR to make that change?

BTW, what tool did you used to catch it? If you find any other place for improvement, please feel free to make those changes as well.

**Comment by elfring** [comment]
>Would you like to open a PR to make that change?

I would find it nice if the possible adjustment for a single assignment statement can be integrated also directly by an other contributor.


>BTW, what tool did you used to catch it?

Such source code can be searched and replaced also by the means of regular expressions.
