### ISSUE TITLE
Sediments correction in isostatic Moho calculation

### ISSUE THREAD

**Issue by MoSobh** [fatiando/harmonica#300]
I am using hm.isostasy_airy to estimate the Airy isostatic Moho to compare it with the seismic Moho estimate.
I am wondering if it is possible to consider sediments load in the isostatic calculations
Thanks in advance!

**Comment by santisoler** [comment]
Hi @MoSobh . Thanks for opening this issue and sorry for the huge delay on my reply.

Currently the `isostasy_airy()` function implements a very simple model of crust + mantle (with water, optionally), so as it is it cannot consider more complex scenarios like sediments load or different densities for the crust.

I'm not entirely happy with how this function works and its interface. I'm sure it needs more work in thinking how we can rewrite it to make it more general purpose.
Moreover, right now it assumes that any negative height is filled with water, which might not be the case in some places of the world where the topography is below sea level but not filled with water.

Feel free to suggest changes if you can think of better solutions!
