### ISSUE TITLE
Replace cartopy with pygmt in docs

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#317]
**Description of the suggestion:**

Would be great if the maps in the User Guide are done through PyGMT instead of Cartopy.
To do so we need to change how the maps are done and include `pygmt` and `gmt` as dependencies both in `environment.yml` and in `envs/requirements-docs.txt`.

**Comment by mdtanker** [comment]
I'm happy to do this! Let me know and I'll start working on it.

**Comment by santisoler** [comment]
That would be awesome @mdtanker ! Feel free to start whenever you want. I'll assign you to this issue so anyone else interested knows that you're working on it.

**Comment by mdtanker** [comment]
Okay great, I'll start converting them. I've just finished converting the 6 `User Guide - Sample Data` examples, and will start working on the `Gallery` examples.
