### ISSUE TITLE
Better default for depth in equivalent sources

### ISSUE THREAD

**Issue by leouieda** [fatiando/harmonica#424]
**Description of the desired feature:**

From chats with @indiauppal and @birocoles, I learned that Dampney (1969; the original equivalent source paper) advises using depths between 2.5 and 6 times the source spacing (assuming sources in a regular grid). For sources beneath data, like  we use here, a sensible default is 4.5 times the median distance between sources. Me and @indiauppal tested this default and it works well most of the time. Tweaking is always good but this would provide a more sensible default than the fixed value we currently use.

This would break backwards compatibility. I'm not too worried since our docs say that you should always set the `depth` by hand. So changing the default will likely make the interpolation better for the few people who were using the classes without following our advice. But I can do the warning dance if others think it's necessary (but it will take longer to implement).

**Are you willing to help implement and maintain this feature?** 

Yes. But very happy to let someone else do it (😉 @indiauppal)

**Comment by santisoler** [comment]
Just to clarify, the depth should be set to 4.5 times the median distance between first neighbor sources, right?

If that's true, then we can use:
```python
depth = verde.median_distance(coordinates, k_nearest=1)
```

Is this the idea?

**Comment by indiauppal** [comment]
Should we take the mean of the median distances?
`depth = np.mean(verde.median_distance(coordinates, k_nearest=1)) * 4.5`

**Comment by leouieda** [comment]
I guess the mean would be better? Then it wouldn't favor close points. Perhaps it would be good to have a `verde.mean_distance` function as well.
