### ISSUE TITLE
PyGMT figures are not being showed in the latest docs

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#473]
**Page that contains the error or needs to be improved (paste link):** 

The PyGMT figures we generate while building the docs are not being correctly added to the `dev` versions of the Harmonica docs.

For example, compare the Gravity Disturbance page in:
- 0.6.0: https://www.fatiando.org/harmonica/v0.6.0/user_guide/gravity_disturbance.html
- dev: https://www.fatiando.org/harmonica/dev/user_guide/gravity_disturbance.html

I suspect the issue might come from a combination of PyGMT and jupyter-sphinx.

**Comment by santisoler** [comment]
Thanks for pointing to that line @leouieda. I've created a patch for this by explicitly setting `method="notebook"` in the user guide (#474). But maybe we can set this through a env var? Or maybe this deserves opening an issue in PyGMT adding an envvar to control this.

**Comment by leouieda** [comment]
I was adding a hidden cell that sets this globally for each page. But this deserves a fix in PyGMT.
