### ISSUE TITLE
Ugly docstrings generated by Sphinx

### ISSUE THREAD

**Issue by santisoler** [fatiando/harmonica#58]
**Description of the problem**

On the `dev` version of the Harmonica documentation, Sphinx is not compiling the docstrings right.
For example, on [`normal_gravity`](https://www.fatiando.org/harmonica/dev/api/generated/harmonica.normal_gravity.html#harmonica.normal_gravity) docstring the Parameters and Returns mix the variable name with the variable type.

I leave a screenshot of the current `normal_gravity` docstring.
![harmonica-docs](https://user-images.githubusercontent.com/11541317/56313375-dc0df880-6128-11e9-8e4b-1817006d38d4.png)

**Comment by leouieda** [comment]
This is a bug in the `sphinx_rtd_theme` 0.4.3 (rtfd/sphinx_rtd_theme#750). Could you please try setting the version in the `environment.yml` and `requirements-dev.txt` to `=0.4.2` and see is that fixes it?

**Comment by santisoler** [comment]
@leouieda I changed the `sphinx_rtd_theme` to `0.4.2` and `0.4.1` on `environment.yml` and built the docs locally without any improvement.

I've realized that `sphinx` has released a new `2.0.0` version a few weeks ago.
With the following setup, it works well:
- `sphinx = 1.8.5`
- `sphinx_rtd_theme = 0.4.3`

So I think the problem is with `sphinx` and not with the theme.

**Comment by leouieda** [comment]
Oh, that's good to know. Would you mind opening a PR to pin sphinx to 1.8.5? We'll need this until there is a fix for all of our projects (verde, rockhound, pooch).
