### ISSUE TITLE
Page about the coordinate systems

### ISSUE THREAD

**Issue by leouieda** [fatiando/harmonica#68]
We need a documentation page describing our coordinate system conventions.

**Comment by prisae** [comment]
I did this recently for empymod. The example (particularly the coordinate-system figure) might be useful to get this issue going:

https://empymod.readthedocs.io/en/stable/examples/coordinate_system.html

**Comment by santisoler** [comment]
Thanks @prisae for the motivation. We should have tackled this issue long time ago, so this could be a good opportunity to do so.
