### ISSUE TITLE
Sample dataset: Global gravity from ICGEM

### ISSUE THREAD

**Issue by leouieda** [fatiando/harmonica#9]
**Description of the desired feature**

A global gravity grid from an ICGEM spherical harmonic model (like EIGEN-6c4) would be great to showcase our gravity processing and any global methods, like tesseroid topographic correction. This should be an `xarray.Dataset` with raw gravity (no corrections), latitude, longitude, and ellipsoid height. To make things easier, gravity should probably be calculated on top of topography so that Bouguer corrections work reasonably.

**Comment by santis19** [comment]
@leouieda 
I'll be glad to get into this issue.
By the way, I can use this sample dataset to write an example for the `load_icgem_gdf()` function that is currently being written in #11.

We just need to propose a region of the world.
In the past we have used the Alps and Hawaii, maybe some region of the Southern hemisphere would make a more inclusive Fatiando!
We could ask for ideas in gitter if you agree.
